
import { _mock } from './_mock';

// ----------------------------------------------------------------------

export const USER_STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'pending', label: 'Pending' },
  { value: 'banned', label: 'Banned' },
  { value: 'rejected', label: 'Rejected' },
];

export const _userList = [
  {
    name: 'סהר כליפה',
    email: "saharkal@post.bgu.ac.il",
    studentID: "341234213",
    department: "הנדסת תוכנה",
    degree: "תואר שני",
    status: "לא ידוע",
    gradesAvarage: "91",
    numOfArticles: "3",
    phoneNumber: "0509220305",
    scholarshipName: "None",
    rank: 2,
    gender: "זכר",
    yearOfBirth: "1994",
    supervisor: "רוברט מוסקוביץ",
    fieldOfResearch: "אלגוריתמים",
    topicOfReasearch: "אלגוריתמי קירוב",
    dateOfStartDgree: "12.10.24",
    instituteOfBechlor: "בן גוריון",
    facultyOfBechlor: "הנדסה",
    departmentOfBechlor: "הנדסת תוכנה",
    rankArticles: "A",
  },
  {
    name: 'תומר טל',
    studentID: "341212343",
    email: "tomertal@post.bgu.ac.il",
    phoneNumber: "0529220235",
    department: "הנדסת תוכנה",
    degree: "תואר שני",
    status: "לא ידוע",
    gradesAvarage: "95",
    numOfArticles: "5",
    scholarshipName: "None",
    rank: 3,
    gender: "זכר",
    yearOfBirth: "1994",
    supervisor: "רוברט מוסקוביץ",
    fieldOfResearch: "אלגוריתמים",
    topicOfReasearch: "אלגוריתמי קירוב",
    dateOfStartDgree: "12.10.24",
    instituteOfBechlor: "בן גוריון",
    facultyOfBechlor: "הנדסה",
    departmentOfBechlor: "הנדסת תוכנה",
    rankArticles: "A",
  },
  {
    name: 'גיא פורת',
    studentID: "344534213",
    email: "guyporat@post.bgu.ac.il",
    phoneNumber: "0529210315",
    department: "הנדסת תוכנה",
    degree: "תואר שני",
    status: "לא ידוע",
    gradesAvarage: "91",
    numOfArticles: "3",
    scholarshipName: "None",
    rank: 1,
    gender: "זכר",
    yearOfBirth: "1994",
    supervisor: "רוברט מוסקוביץ",
    fieldOfResearch: "אלגוריתמים",
    topicOfReasearch: "אלגוריתמי קירוב",
    dateOfStartDgree: "12.10.24",
    instituteOfBechlor: "בן גוריון",
    facultyOfBechlor: "הנדסה",
    departmentOfBechlor: "הנדסת תוכנה",
    rankArticles: "A",
  },
  {
    name: 'נמרוד בורג',
    studentID: "211234418",
    email: "nimrodburg@post.bgu.ac.il",
    phoneNumber: "0526000301",
    department: "הנדסת תוכנה",
    degree: "תואר שני",
    status: "לא ידוע",
    gradesAvarage: "93",
    numOfArticles: "2",
    scholarshipName: "None",
    rank: 4,
    gender: "זכר",
    yearOfBirth: "1994",
    supervisor: "רוברט מוסקוביץ",
    fieldOfResearch: "אלגוריתמים",
    topicOfReasearch: "אלגוריתמי קירוב",
    dateOfStartDgree: "12.10.24",
    instituteOfBechlor: "בן גוריון",
    facultyOfBechlor: "הנדסה",
    departmentOfBechlor: "הנדסת תוכנה",
    rankArticles: "A",
  },
  // {
  //   name: 'עומר כהן',
  //   studentID: "211234418",
  //   email: "omercohen@post.bgu.ac.il",
  //   phoneNumber: "0526200301",
  //   department: "הנדסה כימית",
  //   degree: "תואר שני",
  //   status: "לא ידוע",
  //   gradesAvarage: "89",
  //   numOfArticles: "1",
  //   scholarshipName: "None",
  //   rank: 5,
  //   gender: "זכר",
  //   yearOfBirth: "1994",
  //   supervisor: "רוברט מוסקוביץ",
  //   fieldOfResearch: "אלגוריתמים",
  //   topicOfReasearch: "אלגוריתמי קירוב",
  //   dateOfStartDgree: "12.10.24",
  //   instituteOfBechlor: "בן גוריון",
  //   facultyOfBechlor: "הנדסה",
  //   departmentOfBechlor: "הנדסת תוכנה",
  //   rankArticles: "A",
  // },
  // {
  //   name: 'ליטל לוי',
  //   studentID: "211234418",
  //   email: "litallevy@post.bgu.ac.il",
  //   phoneNumber: "0526200301",
  //   department: "הנדסת חשמל",
  //   degree: "תואר שני",
  //   status: "לא ידוע",
  //   gradesAvarage: "92",
  //   numOfArticles: "4",
  //   scholarshipName: "None",
  //   rank: 6,
  //   gender: "נקבה",
  //   yearOfBirth: "1994",
  //   supervisor: "רוברט מוסקוביץ",
  //   fieldOfResearch: "אלגוריתמים",
  //   topicOfReasearch: "אלגוריתמי קירוב",
  //   dateOfStartDgree: "12.10.24",
  //   instituteOfBechlor: "בן גוריון",
  //   facultyOfBechlor: "הנדסה",
  //   departmentOfBechlor: "הנדסת תוכנה",
  //   rankArticles: "A",
  // },
];